name: addiosognidigloria
favicon: null
layout_spectrum: 0.2656570668332279
typography_spectrum: 0.3462661253288388
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.1449351527262479
  lightness: 0.3654966144822538
  saturation: 0.7081479420885444
  rhythmicContrast: 0.038072600262239575
purpose: []
