name: Natalino Dueville
favicon: null
layout_spectrum: 0.017024356173351407
typography_spectrum: 0.9545262961182743
title: Natalino Dueville
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#eaeaea'
    - '#2c2c2c'
    - '#b6b6b6'
    - '#707070'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
