name: addiosognidigloria
favicon: null
layout_spectrum: 0.015137721784412861
typography_spectrum: 0.8416358844842762
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.0914482690859586
  lightness: 0.22602403350174427
  saturation: 0.9644050290808082
  rhythmicContrast: 0.5669584597926587
purpose: []
