name: addiosognidigloria
favicon: null
layout_spectrum: 0.017024356173351407
typography_spectrum: 0.9545262961182743
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8308284445665777
  lightness: 0.9460755195468664
  saturation: 0.8681510728783906
  rhythmicContrast: 0.9468802297487855
purpose: []
